fix AttributeError
The existing code produced the following error when calling the status
endpoint:'

AttributeError: 'list' object has not attribute 'copy'

Switching to a list comprehension clears this error up.

Signed-off-by: Gregory Setterholm <gregoryx.setterholm@intel.com>