Use correct entries list to generate AuthorizationException
The `entries` list does not contain TpStateEntry messages, so the code will
throw an exception when generating the AuthorizationException:

    addresses = [e.address for e in entries]
AttributeError: 'str' object has no attribute 'address'

Signed-off-by: Andrew Backer <awbacker@gmail.com>