Fix missing python3 netifaces dependencies in the CI docs build.
Removes this error:
Traceback (most recent call last):
  File "/project/sawtooth-core/bin/validator", line 34, in <module>
    from sawtooth_validator.server.cli import main
  File "/project/sawtooth-core/validator/sawtooth_validator/server/cli.py", line 20, in <module>
    import netifaces
ImportError: No module named 'netifaces'

Signed-off-by: Cian Montgomery <cian.montgomery@intel.com>